---
apiVersion: triggers.tekton.dev/v1alpha1
kind: Trigger
metadata:
  name: pipeline-pull-request
spec:
  interceptors:
    - github:
        secretRef:
          secretName: ci-webhook
          secretKey: secret
        eventTypes:
          - pull_request
    - cel:
        filter: >-
          body.repository.name == 'pipeline' &&
          body.action in ['opened', 'synchronize', 'labeled', 'unlabeled', 'reopened']
        overlays:
          - key: git_clone_depth
            expression: "string(body.pull_request.commits + 1.0)"
  bindings:
    - ref: tekton-ci-github-base
    - ref: tekton-ci-webhook-pull-request
    - ref: tekton-ci-webhook-pr-labels
    - ref: tekton-ci-clone-depth
  template:
    ref: tekton-pipeline-ci-pipeline
---
apiVersion: triggers.tekton.dev/v1alpha1
kind: Trigger
metadata:
  name: pipeline-issue-comment
spec:
  interceptors:
    - github:
        secretRef:
          secretName: ci-webhook
          secretKey: secret
        eventTypes:
          - issue_comment
    - cel:
        filter: >-
          body.repository.name == 'pipeline' &&
          body.action == 'created' &&
          'pull_request' in body.issue &&
          body.issue.state == 'open' &&
          body.comment.body.matches('^/test($| [^ ]*[ ]*$)')
        overlays:
        - key: add_pr_body.pull_request_url
          expression: "body.issue.pull_request.url"
    - webhook:
        objectRef:
          kind: Service
          name: add-pr-body
          apiVersion: v1
          namespace: tekton-ci
    - cel:
        overlays:
          - key: git_clone_depth
            expression: "string(body.extensions.add_pr_body.pull_request_body.commits + 1.0)"
  bindings:
    - ref: tekton-ci-github-base
    - ref: tekton-ci-webhook-comment
    - ref: tekton-ci-clone-depth
    - ref: tekton-ci-webhook-issue-labels
  template:
    ref: tekton-pipeline-ci-pipeline
