apiVersion: triggers.tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: cron
spec:
  serviceAccountName: robot
  triggers:
    - name: cron-trigger
      bindings:
        - ref: binding
      template:
        name: template
