namePrefix: nightly-release-
commonLabels:
  app: tekton.plumbing
commonAnnotations:
  release: nightly
resources:
  - template.yaml
  - trigger.yaml
configurations:
- kustomizeconfig/eventlistener.yaml
- kustomizeconfig/pipeline.yaml
