namePrefix: nightly-release-
commonLabels:
  app: tekton.plumbing
commonAnnotations:
  release: nightly
resources:
  - bindings.yaml
  - serviceaccount.yaml
  - template.yaml
  - eventlistener.yaml
configurations:
- kustomizeconfig/eventlistener.yaml
