apiVersion: v1
kind: ServiceAccount
metadata:
  name: robot
secrets:
- name: nightly-account
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: release-minimal
rules:
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["triggers.tekton.dev"]
  resources: ["eventlisteners", "triggerbindings", "triggertemplates"]
  verbs: ["get", "list"]
- apiGroups: ["tekton.dev"]
  resources: ["pipelineruns", "pipelineresources", "taskruns"]
  verbs: ["create"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: robot-release-minimal
subjects:
- kind: ServiceAccount
  name: robot
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: release-minimal
