commonLabels:
  app: tekton.plumbing
resources:
- images/image-build-trigger.yaml
- release/install_and_test_tekton_release.yaml
- release/install_tekton_release.yaml
- release/nightly-release-logs-trigger.yaml
- release/prerelease_checks.yaml
- release/save-release-logs.yaml
- release/test_tekton_release.yaml
