apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: peribolos-trigger
spec:
  schedule: "30 * * * *"
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: trigger
            env:
              - name: GIT_REPOSITORY
                value: "https://github.com/tektoncd/community"
              - name: GIT_REVISION
                value: "main"
