# Copyright 2020 The Tekton Authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  name: deploy-configmap
spec:
  params:
  - name: gitRepository
    description: URL of the repository that holds configuration
  - name: gitRevision
    description: Git revision
  - name: namespace
    description: Namespace to deploy to in the target cluster
  - name: configPath
    description: Path in the git repo that holds configs
  - name: clusterResource
    description: Name of the cluster resource that points to the target cluster
  - name: configMapName
    description: Name of the configmap resource
  - name: configMapKey
    description: Name of the configmap key where the data is stored
  - name: configMapDescription
    description: Used for a descriptive TaskRun name
  resourcetemplates:
  - apiVersion: tekton.dev/v1alpha1
    kind: PipelineResource
    metadata:
      name: git-source-$(uid)
    spec:
      type: git
      params:
      - name: revision
        value: $(params.gitRevision)
      - name: url
        value: https://$(params.gitRepository)
  - apiVersion: tekton.dev/v1alpha1
    kind: TaskRun
    metadata:
      name: deploy-configmap-$(params.configMapDescription)-$(uid)
    spec:
      taskSpec:
        inputs:
          params:
          - name: configPath
          - name: namespace
          - name: configMapName
          - name: configMapKey
          resources:
          - name: source
            type: git
          - name: targetCluster
            type: cluster
        stepTemplate:
          env:
          - name: KUBECONFIG
            value: /workspace/$(inputs.resources.targetCluster.name)/kubeconfig
        steps:
        - name: fetch-current-config
          image: gcr.io/tekton-releases/dogfooding/kubectl
          script: |
            #!/bin/sh
            set -ex
            kubectl get configmap -n $(inputs.params.namespace) \
              $(inputs.params.configMapName) -o template \
              --template='{{ index .data "$(inputs.params.configMapKey)" }}' > \
               /workspace/$(inputs.params.configMapKey) || \
               rm /workspace/$(inputs.params.configMapKey)
        - name: deploy
          image: gcr.io/tekton-releases/dogfooding/kubectl
          script: |
            #!/bin/sh
            set -ex
            if [ ! -f /workspace/$(inputs.params.configMapKey) ]; then
              echo "First time deployment"
              kubectl create configmap $(inputs.params.configMapName) \
                --from-file=$(inputs.params.configMapKey)=$(inputs.resources.source.path)/$(inputs.params.configPath) \
                -n $(inputs.params.namespace)
                exit 0
            fi
            echo "diff [current-config] [new config]"
            has_diff=0
            diff /workspace/$(inputs.params.configMapKey) \
              $(inputs.resources.source.path)/$(inputs.params.configPath) || has_diff=1
            if [ $has_diff -eq 0 ]; then
              echo "No change in config detected. Nothing to be done."
              exit 0
            fi
            # Apply configuration changes
            kubectl create configmap $(inputs.params.configMapName) \
              --from-file=$(inputs.params.configMapKey)=$(inputs.resources.source.path)/$(inputs.params.configPath) \
              --dry-run -o yaml | \
              kubectl replace configmap $(inputs.params.configMapName) -n $(inputs.params.namespace) -f -
      inputs:
        params:
        - name: configPath
          value: $(params.configPath)
        - name: namespace
          value: $(params.namespace)
        - name: configMapName
          value: $(params.configMapName)
        - name: configMapKey
          value: $(params.configMapKey)
        resources:
        - name: source
          resourceRef:
            name: git-source-$(uid)
        - name: targetCluster
          resourceRef:
            name: $(params.clusterResource)
