---
apiVersion: triggers.tekton.dev/v1beta1
kind: EventListener
metadata:
  name: tekton-ci
spec:
  serviceAccountName: tekton-ci-workspace-listener
  triggerGroups:
    - name: github-tektoncd-pr-group
      interceptors:
        - name: "Validate GitHub payload and filter on eventType"
          ref:
            name: "github"
          params:
            - name: "secretRef"
              value:
                secretName: github-secret
                secretKey: secretToken
            - name: "eventTypes"
              value:
                - "pull_request"
        - name: "Filter the GitHub org and actions and add git_clone_depth"
          ref:
            name: "cel"
          params:
            - name: "filter"
              value: >-
                body.repository.full_name.startsWith('tektoncd/') &&
                body.action in ['opened', 'synchronize', 'labeled', 'unlabeled', 'reopened']
            - name: "overlays"
              value:
                - key: git_clone_depth
                  expression: "string(body.pull_request.commits + 1.0)"
      triggerSelector:
        namespaceSelector:
          matchNames:
            - tekton-ci
        labelSelector:
          matchLabels:
            ci.tekton.dev/trigger-type: github.pull-request
    - name: github-tektoncd-issue-comment-group
      interceptors:
        - name: "Validate GitHub payload and filter on eventType"
          ref:
            name: "github"
          params:
            - name: "secretRef"
              value:
                secretName: github-secret
                secretKey: secretToken
            - name: "eventTypes"
              value:
                - "issue_comment"
        - name: "Filter the GitHub org and actions state text"
          ref:
            name: "cel"
          params:
            - name: "filter"
              value: >-
                body.repository.full_name.startsWith('tektoncd/') &&
                body.action == 'created' &&
                'pull_request' in body.issue &&
                body.issue.state == 'open' &&
                body.comment.body.matches('^/test($| [^ ]*[ ]*$)')
            - name: "overlays"
              value:
                - key: add_pr_body.pull_request_url
                  expression: "body.issue.pull_request.url"
        - name: "Fetch the PR body"
          ref:
            name: "webhook"
          params:
            - name: "objectRef"
              value:
                kind: Service
                name: add-pr-body
                apiVersion: v1
                namespace: tektonci
        - name: "Add git_clone_depth"
          ref:
            name: "cel"
          params:
            - name: "overlays"
              value:
                - key: git_clone_depth
                  expression: "string(body.extensions.add_pr_body.pull_request_body.commits + 1.0)"
      triggerSelector:
        namespaceSelector:
          matchNames:
            - tekton-ci
        labelSelector:
          matchLabels:
            ci.tekton.dev/trigger-type: github.issue-comment