apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: yamllint
  namespace: tektonci
  description: |
    Lint yamls
spec:
  params:
  - name: folders
    description: The folders to lint with yamllint
  workspaces:
    - name: source
  steps:
  - name: lint
    image: gcr.io/tekton-releases/dogfooding/yamllint:latest
    workingDir: $(workspaces.source.path)
    script: |
      #!/bin/sh
      set -ex
      yamllint $(params.folders)
