apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: golang-lint
  namespace: tektonci
  description: |
    Lint golang source using golangci-lint
spec:
  params:
  - name: version
    description: golangci-lint version to use
    default: "v1.27.0"
  - name: flags
    description: flags to use for the golangci-lint run command
    default: --verbose
  - name: GOOS
    description: "running operating system target"
    default: linux
  - name: GOARCH
    description: "running architecture target"
    default: amd64
  - name: GO111MODULE
    description: "value of module support"
    default: auto
  resources:
    inputs:
      - name: source
        type: git
  steps:
  - name: lint
    image: golangci/golangci-lint:$(params.version)
    script: |
      #!/bin/sh
      set -ex
      cd /workspace/source/
      golangci-lint run $(params.flags)
    env:
    - name: GOPATH
      value: /workspace
    - name: GOOS
      value: "$(params.GOOS)"
    - name: GOARCH
      value: "$(params.GOARCH)"
    - name: GO111MODULE
      value: "$(params.GO111MODULE)"
---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: yamllint
  namespace: tektonci
  description: |
    Lint yamls
spec:
  params:
  - name: folders
    description: The folders to lint with yamllint
  workspaces:
    - name: source
  steps:
  - name: lint
    image: gcr.io/tekton-releases/dogfooding/yamllint:latest
    workingDir: $(workspaces.source.path)
    script: |
      #!/bin/sh
      set -ex
      yamllint $(params.folders)
