apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: tekton-golang-tests
  namespace: tektonci
spec:
  params:
    - name: gitCloneDepth
      description: Number of commits in the change + 1
    - name: fileFilterRegex
      description: Names regex to be matched in the list of modified files
    - name: checkName
      description: The name of the GitHub check that this pipeline is used for
    - name: gitHubCommand
      description: The command that was used to trigger testing
    - name: package
      description: package (and its children) under test
    - name: folders
      type: array
      description: The folders to test
  resources:
    - name: source
      type: git
  tasks:
  - name: unit-tests
    conditions:
    - conditionRef: "check-git-files-changed"
      params:
      - name: gitCloneDepth
        value: $(params.gitCloneDepth)
      - name: regex
        value: $(params.fileFilterRegex)
      resources:
      - name: source
        resource: source
    - conditionRef: "check-name-matches"
      params:
      - name: gitHubCommand
        value: $(params.gitHubCommand)
      - name: checkName
        value: $(params.checkName)
    taskRef:
      apiVersion: custom.tekton.dev/v1alpha1
      kind: TaskLoop
      name: golang-tests
    params:
    - name: context
      value: $(params.folders)
    - name: version
      value: "1.15"
    resources:
      inputs:
      - name: source
        resource: source