apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: peribolos
spec:
  params:
  - name: configPath
    default: org/org.yaml
  resources:
    inputs:
      - name: repo
        type: git
  steps:
  - name: peribolos
    image: gcr.io/k8s-prow/peribolos:v20201110-efa5cb6a5e
    command:
    - /bin/sh
    args:
    - -c
    - |
      set -ex
      /peribolos -config-path /workspace/repo/$(params.configPath) -fix-org -fix-org-members -fix-teams -fix-team-repos -fix-team-members -github-token-path /etc/github/bot-token -confirm=true
    volumeMounts:
    - name: github-oauth
      mountPath: /etc/github
  volumes:
  - name: github-oauth
    secret:
      secretName: bot-token-github
