---
apiVersion: triggers.tekton.dev/v1alpha1
kind: Trigger
metadata:
  name: community-pull-request
  labels:
    ci.tekton.dev/trigger-type: github.pull-request
spec:
  interceptors:
    - cel:
        filter: >-
          body.repository.name == 'community'
  bindings:
    - ref: tekton-ci-github-base
    - ref: tekton-ci-webhook-pull-request
    - ref: tekton-ci-webhook-pr-labels
    - ref: tekton-ci-clone-depth
  template:
    ref: tekton-community-ci-pipeline
---
apiVersion: triggers.tekton.dev/v1alpha1
kind: Trigger
metadata:
  name: community-issue-comment
  labels:
    ci.tekton.dev/trigger-type: github.issue-comment
spec:
  interceptors:
    - cel:
        filter: >-
          body.repository.name == 'community'
  bindings:
    - ref: tekton-ci-github-base
    - ref: tekton-ci-webhook-comment
    - ref: tekton-ci-clone-depth
    - ref: tekton-ci-webhook-issue-labels
  template:
    ref: tekton-community-ci-pipeline
