kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: config-map-updater
rules:
- apiGroups: ["*"]
  resources: ["configmaps"]
  verbs: ["get", "list", "patch", "update"]
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: prow-config-bot
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: prow-config-bot-config-map-updater
subjects:
- kind: ServiceAccount
  name: prow-config-bot
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: config-map-updater
