apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: config-map-updater
  namespace: default
rules:
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["get", "list", "patch", "update"]
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: prow-config-bot
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: prow-config-bot-config-map-updater
  namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: config-map-updater
subjects:
- kind: ServiceAccount
  name: prow-config-bot
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: config-map-updater
  namespace: github-admin
rules:
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["get", "list", "patch", "update"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: default-map-updater
  namespace: github-admin
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: config-map-updater
subjects:
- kind: ServiceAccount
  name: default
