apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerBinding
metadata:
  name: trigger-to-build-and-push-image
spec:
  params:
  - name: buildUUID
    value: $(body.buildUUID)
  - name: gitRepository
    value: $(body.gitRepository)
  - name: gitRevision
    value: $(body.gitRevision)
  - name: contextPath
    value: $(body.contextPath)
  - name: registry
    value: $(body.registry)
  - name: namespace
    value: $(body.namespace)
  - name: imageName
    value: $(body.imageName)
  - name: imageTags
    value: $(body.imageTags)
---
apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerBinding
metadata:
  name: trigger-to-build-and-push-image-platform
spec:
  params:
  - name: platforms
    value: $(body.platforms)
