apiVersion: apps/v1
kind: Deployment
metadata:
  name: pipelinerun-logs-deployment
  labels:
    app: pipelinerun-logs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pipelinerun-logs
  template:
    metadata:
      labels:
        app: pipelinerun-logs
    spec:
      containers:
      - name: pipelinerun-logs
        image: github.com/tektoncd/plumbing/pipelinerun-logs/cmd/http
        args:
        - "--project"
        - "tekton-releases"
        - "--cluster"
        - "dogfooding"
        - "--namespace"
        - "default"
        - "--hostname"
        - "0.0.0.0"
        - "--port"
        - "9999"
        ports:
        - containerPort: 9999
