---
apiVersion: tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: tekton-ci-webhook
  namespace: tektonci
spec:
  serviceAccountName: tekton-ci-listener
  serviceType: NodePort
  triggers:
    - name: pull-request-trigger
      interceptors:
        - github:
            secretRef:
              secretName: ci-webhook
              secretKey: secret
            eventTypes:
              - pull_request
        - cel:
            filter: "body.action == 'opened' || body.action == 'synchronize'"
            # overlays:
            # - key: extensions.git_clone_depth
            #   expression: "body.pull_request.commits + 1"
      bindings:
        - name: tekton-ci-webhook-pull-request
      template:
        name: tekton-ci-pipeline
---
apiVersion: tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: github-check-done
  namespace: tektonci
spec:
  serviceAccountName: tekton-ci-listener
  triggers:
    - name: github-check-done
      interceptors:
        - cel:
            filter: "body.taskRun.metadata.labels['tekton.dev/kind'] == 'ci'"
      bindings:
        - name: tekton-ci-taskrun-cloudevent
        - name: tekton-ci-check-complete
      template:
        name: tekton-ci-github-check-update
---
apiVersion: tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: github-check-start
  namespace: tektonci
spec:
  serviceAccountName: tekton-ci-listener
  triggers:
    - name: github-check-start
      interceptors:
        - cel:
            filter: "body.taskRun.metadata.labels['tekton.dev/kind'] == 'ci'"
      bindings:
        - name: tekton-ci-taskrun-cloudevent
        - name: tekton-ci-check-pending
      template:
        name: tekton-ci-github-check-update
