---
apiVersion: triggers.tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: tekton-ci-webhook
  namespace: tektonci
spec:
  serviceAccountName: tekton-ci-listener
  serviceType: NodePort
  triggers:
    - name: pull-request-trigger
      interceptors:
        - github:
            secretRef:
              secretName: ci-webhook
              secretKey: secret
            eventTypes:
              - pull_request
        - cel:
            filter: >-
              body.action == 'opened' || body.action == 'synchronize'
            overlays:
            - key: extensions.git_clone_depth
              expression: "string(body.pull_request.commits + 1.0)"
      bindings:
        - name: tekton-ci-webhook-pull-request
      template:
        name: tekton-ci-pipeline
    - name: comment-trigger
      interceptors:
        - github:
            secretRef:
              secretName: ci-webhook
              secretKey: secret
            eventTypes:
              - issue_comment
        - cel:
            filter: >-
              body.action == 'created' &&
              'pull_request' in body.issue &&
              body.issue.state == 'open' &&
              body.comment.body.matches('^/test($| [^ ]*[ ]*$)')
            overlays:
            - key: add_pr_body.pull_request_url
              expression: "body.issue.pull_request.url"
        - webhook:
            objectRef:
              kind: Service
              name: add-pr-body
              apiVersion: v1
              namespace: tektonci
        - cel:
            overlays:
            - key: extensions.git_clone_depth
              expression: "string(body.add_pr_body.pull_request_body.commits + 1.0)"
      bindings:
        - name: tekton-ci-webhook-comment
      template:
        name: tekton-ci-pipeline
    - name: trigger-check-pr-labels
      interceptors:
        - github:
            secretRef:
              secretName: ci-webhook
              secretKey: secret
            eventTypes:
              - pull_request
        - cel:
            filter: >-
              (body.action == 'opened' ||
               body.action == 'labeled' ||
               body.action == 'unlabeled')
      bindings:
        - name: trigger-to-check-pr-labels
      template:
        name: check-pull-request-labels