apiVersion: tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  name: tekton-ci-pipeline
  namespace: tektonci
spec:
  params:
  - name: buildUUID
    description: UUID used to track a CI Pipeline Run in logs
  - name: package
    description: org/repo
  - name: pullRequestNumber
    description: The pullRequestNumber
  - name: gitRepository
    description: The git repository that hosts context and Dockerfile
  - name: gitRevision
    description: The Git revision to be used.
  - name: gitCloneDepth
    description: Number of commits in the change + 1
  resourcetemplates:
  - apiVersion: tekton.dev/v1alpha1
    kind: PipelineRun
    metadata:
      name: tekton-noop-check-$(uid)
      labels:
        prow.k8s.io/build-id: $(params.buildUUID)
        tekton.dev/check-name: tekton-noop-check
        tekton.dev/kind: ci
        tekton.dev/pr-number: $(params.pullRequestNumber)
      annotations:
        tekton.dev/gitURL: "$(params.gitRepository)"
    spec:
      serviceAccountName: tekton-ci-jobs
      pipelineRef:
        name: tekton-noop-check
      params:
        - name: passorfail
          value: pass
        - name: message
          value: "BuildUUID#: $(params.buildUUID), Package: $(params.package), Repo: $(params.gitRepository), Revision: $(params.gitRevision)"
        - name: gitCloneDepth
          value: $(params.gitCloneDepth)
        - name: fileFilterRegex
          value: ".*"
      resources:
      - name: source
        resourceSpec:
          type: git
          params:
          - name: revision
            value: $(params.gitRevision)
          - name: url
            value: $(params.gitRepository)
          - name: depth
            value: $(params.gitCloneDepth)
      - name: starttrigger
        resourceRef:
          name: github-check-start
      - name: endtrigger
        resourceRef:
          name: github-check-done
  - apiVersion: tekton.dev/v1alpha1
    kind: PipelineRun
    metadata:
      name: tekton-noop-check-fail-$(uid)
      labels:
        prow.k8s.io/build-id: $(params.buildUUID)
        tekton.dev/check-name: tekton-noop-check-fail
        tekton.dev/kind: ci
        tekton.dev/pr-number: $(params.pullRequestNumber)
      annotations:
        tekton.dev/gitURL: "$(params.gitRepository)"
    spec:
      serviceAccountName: tekton-ci-jobs
      pipelineRef:
        name: tekton-noop-check
      params:
        - name: passorfail
          value: fail
        - name: message
          value: "BuildUUID#: $(params.buildUUID), Package: $(params.package), Repo: $(params.gitRepository), Revision: $(params.gitRevision)"
        - name: gitCloneDepth
          value: $(params.gitCloneDepth)
        - name: fileFilterRegex
          value: "(tekton/ci|tekton-demo)"
      resources:
      - name: source
        resourceSpec:
          type: git
          params:
          - name: revision
            value: $(params.gitRevision)
          - name: url
            value: $(params.gitRepository)
          - name: depth
            value: $(params.gitCloneDepth)
      - name: starttrigger
        resourceRef:
          name: github-check-start
      - name: endtrigger
        resourceRef:
          name: github-check-done
