apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: tekton-ci-reset-check-status
  namespace: tektonci
  description: |
    Triggers the reset of the status of a check before the check is executed.
spec:
  params:
    - name: checkName
      description: Description of the check being reset
      type: string
  resources:
    outputs:
      - name: trigger
        type: cloudEvent
  steps:
  - name: noop
    image: busybox
    script: |
      #!/bin/sh
      echo "Trigger the reset of status for $(params.checkName)"
